
@host = http://localhost
@port = 5026
@token = CfDJ8Ip7dGhlioVKogTBOl9a_KYG7v3-lAnCNIAIGTxpoKN3wLupgSgyTNz20XlGot6fooFCx2wi1LdrzlVFhfIHBXiooIz2Pupo0EII3g2f69XyKUGcvQeD14V-PRHcS9GTsF_h7Man9GehWynPkq3JP3S6OHGrQ49Ars3X_A5uem7N3tE_brgvK05pIDsb2vVUj6a5NSWslJIH2ICPRZTM0_FshsweqP8_VSiFKPtT6FlqLWuB0Oq-DcvihJpwnG3Gv0E0O9eDMOLzGRyMiQjYMxG_vAiKjb839NUBa-XeGbljU9z7wM2F2dnnd2nZexOTJmfpvEgn9pGhxaZMJLqyT_gkRJ1XRvV7evIq74DAQ4HS5zrrfaxgGLBMY9umX5Uz6DhbauL6LOm3xn1wjhkXVh7GUmxmte1cHKdup_D18O-h1xb4cg6ysLcVmziH_ZmJ4jLbY68SPnqaW1kw5TeA1oozBHPk6u1-u8xq0zDxRyvE3gMZPheDLmtaz62CXrepjg4LzMxMLbTBqu8ovUfYvAtK0yvioMffY6HZGw1J3DUCx7rPsBLMt3NiN8xfKZ73PsUK-p1P12iHEO7M6wLPM9Vg4r1JiFX5dqZyl2IZApCepV8j3pa7fLafr5pXBIR8cohSRNT76A9wtgOhIHTIgx5l29Dw5JQSPuz5RdZwnUO5QVV6yJED7j2qsfhdku1dWcxQ3qK-7UZNvc8bQfUUVUa_KFP-__dvIknyYtPkgAuhO6O49LHc82AVsbfEm82d_rCEB_S9Niy01GpKTASaSQ5cwXwbe4OA_bIegF-64x4v
@Restaurants_API_HostAddress = {{host}}:{{port}}

GET {{Restaurants_API_HostAddress}}/api/restaurants?pageSize=5&pageNumber=1&sortBy=Name&sortDirection=Ascending
Authorization: Bearer {{token}}

###
GET {{Restaurants_API_HostAddress}}/api/restaurants/5
Authorization: Bearer {{token}}

###

POST {{Restaurants_API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
      "Name": "new",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true, 
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###
DELETE {{Restaurants_API_HostAddress}}/api/restaurants/12
Authorization: Bearer {{token}}
Accept: application/json

###
PATCH {{Restaurants_API_HostAddress}}/api/restaurants/12
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "test2",
  "description": "test2",
  "hasDelivery": true
}

###
@restaurantId = 5

POST {{Restaurants_API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

{
  "Name": "Spaghetti",
  "Description": "Classic Italian pasta"
}

### 

GET {{Restaurants_API_HostAddress}}/api/restaurants/5/dishes

### 

DELETE {{Restaurants_API_HostAddress}}/api/restaurants/5/dishes

###
POST {{Restaurants_API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Password1!"
}

###
POST {{Restaurants_API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "Password1!"
}

###
POST {{Restaurants_API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userEmail": "testuser@test.com",
  "roleName": "User"
}