
@host = http://localhost
@port = 5026
@token = CfDJ8Ip7dGhlioVKogTBOl9a_Ka6A76UgC0mm3FHifwCWuQRJeQCoR7hCGufAzLg9wvn6x8k7UeenXvTRuWrZIKR-EmENdzCgiysk5mW086dHd7-p1CI-CROssltHWpQK287IJsq-pby5bh49S1Ke9xyGxa31Zt0e_sf3sWIqG9TIvIFSk2xgfxie9pj5IpnEkVZi3GCAST02zC_wdrD0IS3m-XvBAxzviZk1mNGHG0ujWzgAlFOlCB3_x2Nk-Y754VjJNENnLTCTvBt4YXHoxRj1XUDiW7Xni4sTBGg9Lc3Xn17xoBErnzQ_qGFZ7RtELAa-dSJPa25ItRer0yyzabDTjqUXn59fMZsBUt_3NleYGQ-4MpXVAd8glKLXosHpmODZljtQyyFD0RmeqaNM2TK1RBm3QJ6SSLodsG9vKwixrPBof__gmZHZlQTdUe3JpGyRXJMMGZ7SM0mijPaby-ZAUKmjGOs4qbTG_pyDUyrcKihoe14MUuWTVtfPqWJJVyeLrKhrRsMcvjmOQt_j7LYcndhb6ccwFg2y_xQFKDwL6lRhxLyuQ2ww_Zu1Uyc-yz8Qge8_GLfsucGWmOsKIOHWloOlxYwLaGD7JJKVgUCePwXh_Vfyv41r9TjBgnD0NviwoJSfr_BHkclCnt_z7dU1Zc22PAW09DpdyDuLtPGehTzzge2aHNmFDEFChkfURMLisOuL-5QDNtKlDN1RLyxubeIzDygH174AchXWdD0no-Svi--wGjHfi4A636OaK9224KS3GvvGc4-5TlAsqTcns-ZgkOMd_ObPqcbNTQz3uQY
@Restaurants_API_HostAddress = {{host}}:{{port}}

GET {{Restaurants_API_HostAddress}}/api/restaurants?pageSize=5&pageNumber=1&sortBy=Name&sortDirection=Ascending
Authorization: Bearer {{token}}


###

POST {{Restaurants_API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
      "Name": "new",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true, 
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###
DELETE {{Restaurants_API_HostAddress}}/api/restaurants/12
Authorization: Bearer {{token}}
Accept: application/json

###
PATCH {{Restaurants_API_HostAddress}}/api/restaurants/12
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "test2",
  "description": "test2",
  "hasDelivery": true
}

###
@restaurantId = 5

POST {{Restaurants_API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

{
  "Name": "Spaghetti",
  "Description": "Classic Italian pasta"
}

### 

GET {{Restaurants_API_HostAddress}}/api/restaurants/5/dishes

### 

DELETE {{Restaurants_API_HostAddress}}/api/restaurants/5/dishes

###
POST {{Restaurants_API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Password1!"
}

###
POST {{Restaurants_API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}

###
POST {{Restaurants_API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userEmail": "testuser@test.com",
  "roleName": "User"
}