
@host = http://localhost
@port = 5026
@token = CfDJ8Ip7dGhlioVKogTBOl9a_KZCp1zSHhqSX9fW7YefAnHOXMSpbje5N4HfLWvoHv63fzgdH6Du_SQTqgMDV9DCFoscht2VlEbxVMIy1Iwr867jg_PASuzFqPFhctlsbSlp0N8VO_TouImDhbvATaKOM_ZmepN_3AYJsYsQCllK4-tlpZfYkLC0N4fJSC_3csfgbDRqBbZOOqj7dArZDJGEO2kuezOfBBWx_Rh722AyCU3PjfwCYcZyMnFQ8li-ahRpZoNrBwGs-QB3zumCkFE2uMGbnN9qE2xcMyyDBwYEgPQTZHssf8B26dLbezu2V8lwq1R8glYpmmnW0eqpJAqGeD_7f9W65W3e7SNChBWjD25vmX7DmqR-zGfhs0_Ta3_Y3hYFVGArK9GJkcnD-1ise4NXO08P1EabMTwBkL3ELXk6QApWrUsbZC0yJLk5PffGorVzBbkxWHyW0blbklevYKNcDFLjigAMGkxXMDNPv0z0RRNJI4sg6kf9H2z_-GdktVIoVkHx-tLQwlyfZSAL7J3kT8GScZNMPrmSasQ3qvQ0HS39bRt6ot6W764TnNYwxPYawJJZZgLC8HxB8C3dtFJ-AmULBejPB5M43dpvQrq_-WMLXJSkbkhSnpHmW9fuZca6aydQYJNXWmA4vmbreYb_gkPXRGcIQVzQPEkCjpjOxGJ9CJ5GtXP6va24esxZMQ
@Restaurants_API_HostAddress = {{host}}:{{port}}

GET {{Restaurants_API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}


###

POST {{Restaurants_API_HostAddress}}/api/restaurants
Content-Type: application/json

{
      "Name": "111",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true, 
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###
DELETE {{Restaurants_API_HostAddress}}/api/restaurants/666
Accept: application/json

###
PATCH {{Restaurants_API_HostAddress}}/api/restaurants/8
Content-Type: application/json

{
  "name": "test2",
  "description": "test2",
  "hasDelivery": true
}

###
@restaurantId = 5

POST {{Restaurants_API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

{
  "Name": "Spaghetti",
  "Description": "Classic Italian pasta"
}

### 

GET {{Restaurants_API_HostAddress}}/api/restaurants/5/dishes

### 

DELETE {{Restaurants_API_HostAddress}}/api/restaurants/5/dishes

###
POST {{Restaurants_API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "Password1!"
}

###
POST {{Restaurants_API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "Password1!"
}