
@host = http://localhost
@port = 5026

@Restaurants_API_HostAddress = {{host}}:{{port}}

GET {{Restaurants_API_HostAddress}}/api/restaurants/666
Accept: application/json


###

POST {{Restaurants_API_HostAddress}}/api/restaurants
Content-Type: application/json

{
      "Name": "111",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true, 
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###
DELETE {{Restaurants_API_HostAddress}}/api/restaurants/666
Accept: application/json

###
PATCH {{Restaurants_API_HostAddress}}/api/restaurants/8
Content-Type: application/json

{
  "name": "test2",
  "description": "test2",
  "hasDelivery": true
}